import Head from "next/head";
import Blogs from "@/components/Blogs";
import Hero from "@/components/Hero";
import Footer from "@/components/Footer";


export default function Home() {

  return (
    <>
      <Head>
        <title>CodeBlog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
    <div>
    <h2 className='text-teal-600 text-xl  border-b-2 mb-4  w-fit mx-auto border-teal-600'>Latest Blogs</h2>
    <Blogs />
    </div>
      <Footer />
    </>
  );
}
